<a href="https://colab.research.google.com/github/vasanthk77/my_projects/blob/main/Fake_news_detection1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***PROJECT : FAKE NEWS DETECTION USING LSTMrnn***



1.   import data

1.   indendent and dependent features

1.   cleaning the data using nlp techinques

1.   apply the stemming or lemmatization

1.   declare the vocabulary and apply the onehot_encoding

2.   decalre the embedding with fixed length for corpus docs

2.   create the Model

2.   go for the train_test_split

2.   test the model

2.  calcaute the metrics for the model



In [2]:
import pandas as pd

In [3]:
a=pd.read_csv('train.csv',error_bad_lines=False,engine='python')
df=pd.DataFrame(a)
df.head()

<ipython-input-3-8193aca35fc6>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  a=pd.read_csv('train.csv',error_bad_lines=False,engine='python')
Skipping line 4433: unexpected end of data


id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
## checking the nan values
df.isnull().sum()

id          0
title     118
author    441
text       11
label       0
dtype: int64

In [7]:
## droping nan values
df1=df.dropna()
df1.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [8]:
## independent and dependent features
X=df1.drop('label',axis=1)
y=df1['label']

In [9]:
import tensorflow as tf

In [10]:
## importing all modules which was required for lstm
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [11]:
## take the vocabulary size from your dataset like taking unique wordss
vocab_size=5000

In [12]:
## 3.Data preprocessing using NLP
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import re
nltk.download('punkt')
nltk.download('stopwords')
ps=PorterStemmer()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [13]:
messages=X.copy()
messages.reset_index(inplace=True)

In [14]:
## cleaning the data
corpus=[]
for i in range(0,len(messages)):
  new=re.sub('[^a-zA-Z]',' ',messages['title'][i])
  new=new.lower()
  new=new.split()

  new=[ps.stem(word) for word in new if not word in stopwords.words('english')]
  new=' '.join(new)
  corpus.append(new)

In [16]:
 corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [17]:
## applying one hot encoding for corpus data
onehot_repre=[one_hot(word,vocab_size) for word in corpus]

In [19]:
## here we got index values of words based on vocabulary
onehot_repre

[[2515, 365, 2403, 3752, 3845, 267, 808, 2389, 1131, 179],
 [1772, 2657, 1479, 80, 970, 2481, 4853],
 [4982, 1891, 3623, 580],
 [2386, 4858, 1326, 279, 4418, 2343],
 [2581, 970, 4890, 4401, 1579, 1176, 970, 4430, 3266, 4436],
 [2114,
  3992,
  330,
  2,
  4952,
  3808,
  1959,
  864,
  4760,
  4317,
  2801,
  532,
  1804,
  2946,
  4853],
 [177, 3668, 128, 4896, 1510, 479, 1218, 320, 167, 1573, 719],
 [2117, 1159, 1822, 4210, 1421, 4484, 3808, 1467, 167, 1573, 719],
 [1213, 1909, 2665, 4939, 2396, 1914, 1973, 1566, 3808, 173],
 [885, 2739, 861, 202, 3935, 3148, 130, 3669],
 [685, 2614, 306, 1096, 1113, 939, 4935, 4006, 755, 1469, 4238],
 [279, 4770, 3845, 1914, 3808, 1421],
 [3359, 3653, 3692, 2790, 1236, 51, 2996, 3847, 2436],
 [356, 3888, 3402, 2067, 1307, 1600, 499, 167, 1573, 719],
 [1032, 3003, 2876, 2451, 2386, 167, 1573, 719],
 [3986, 3915, 3794, 2284, 3248, 2038, 4829, 3886, 2703, 395],
 [2391, 3661, 2657],
 [2683, 2993, 873, 3599, 3808, 4732, 1299, 4853],
 [900, 364, 1479, 388

In [20]:
corpus[10]

'russian research discov secret nazi militari base treasur hunter arctic photo'

In [21]:
onehot_repre[10] ## one hot representation for copurs 100th sentence

[685, 2614, 306, 1096, 1113, 939, 4935, 4006, 755, 1469, 4238]

In [24]:
## using padding we can fixed length for every corpus sentence bcoz we make sure that we need to fixed length for every sentence
sent_length=15
embedding_layer=pad_sequences(onehot_repre,padding='post',maxlen=sent_length) ## post add zeros at end of the words
#pre add zeros before words
print(embedding_layer)

[[2515  365 2403 ...    0    0    0]
 [1772 2657 1479 ...    0    0    0]
 [4982 1891 3623 ...    0    0    0]
 ...
 [3344 4697 3993 ...    0    0    0]
 [1928 3895 2363 ...    0    0    0]
 [4955  478 1932 ...    0    0    0]]


In [26]:
embedding_layer[1]

array([1772, 2657, 1479,   80,  970, 2481, 4853,    0,    0,    0,    0,
          0,    0,    0,    0], dtype=int32)

In [28]:
## Model creation

embedding_vector_features=100
model=Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(200)) ## with 200 neurons
model.add(Dense(1,activation='sigmoid'))  ## output layer
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [30]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 15, 100)           500000    
                                                                 
 lstm_1 (LSTM)               (None, 200)               240800    
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 741001 (2.83 MB)
Trainable params: 741001 (2.83 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [32]:
## convert embedded_layers list to arrays
import numpy as np
X=np.array(embedding_layer)
y=np.array(y)

In [35]:
## train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [36]:
## Model Training
model.fit(X_train,y_train,validation_split=0.33,batch_size=100,epochs=10)

Epoch 1/10
19/19 [==============================] - 5s 125ms/step - loss: 0.5817 - accuracy: 0.6584 - val_loss: 0.5145 - val_accuracy: 0.8134
Epoch 2/10
19/19 [==============================] - 2s 92ms/step - loss: 0.2447 - accuracy: 0.9096 - val_loss: 0.3351 - val_accuracy: 0.8480
Epoch 3/10
19/19 [==============================] - 3s 155ms/step - loss: 0.0782 - accuracy: 0.9802 - val_loss: 0.3539 - val_accuracy: 0.8480
Epoch 4/10
19/19 [==============================] - 2s 101ms/step - loss: 0.0459 - accuracy: 0.9884 - val_loss: 0.7227 - val_accuracy: 0.8134
Epoch 5/10
19/19 [==============================] - 2s 98ms/step - loss: 0.0159 - accuracy: 0.9972 - val_loss: 0.5849 - val_accuracy: 0.8201
Epoch 6/10
19/19 [==============================] - 2s 106ms/step - loss: 0.0099 - accuracy: 0.9983 - val_loss: 0.8436 - val_accuracy: 0.8145
Epoch 7/10
19/19 [==============================] - 2s 95ms/step - loss: 0.0055 - accuracy: 0.9994 - val_loss: 0.8018 - val_accuracy: 0.8134
Epoch 8/1

In [37]:
## Model testing
y_pred=model.predict(X_test)
y_pred=np.where(y_pred>0.5,1,0)


37/37 [==============================] - 2s 15ms/step


In [38]:
## Metrics for the data
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [40]:
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
cm=confusion_matrix(y_test,y_pred)
print(cm)
cr=classification_report(y_test,y_pred)
print(cr)

0.8029259896729777
[[536 130]
 [ 99 397]]
              precision    recall  f1-score   support

           0       0.84      0.80      0.82       666
           1       0.75      0.80      0.78       496

    accuracy                           0.80      1162
   macro avg       0.80      0.80      0.80      1162
weighted avg       0.81      0.80      0.80      1162

